name: Publish 

on: 
  workflow_dispatch:
  push:
    branches:
    - main 

env:
  AZURE_WEBAPP_NAME: dummy-api
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - users: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore ./DummyApi.sln

      - name: Build
        run: dotnet build ./DummyApi.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet build ./DummyApi.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"          
